sudo: required
dist: trusty

language: cpp

compiler:
 - gcc

before_install:
 - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list' 
 - wget https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -O - | sudo apt-key add -
 - sudo apt-get update -qq
 - sudo apt-get install -y git
 - sudo apt-get install -y ros-indigo-ros-base python-catkin-tools python-catkin-pkg --force-yes
 - sudo apt-get install -y ros-indigo-geometry-msgs ros-indigo-sensor-msgs ros-indigo-cv-bridge ros-indigo-interactive-markers ros-indigo-visualization-msgs ros-indigo-std-msgs ros-indigo-shape-msgs ros-indigo-actionlib-msgs ros-indigo-common-msgs --force-yes
 - sudo apt-get install -y libglib2.0-0 libglib2.0-dev libjson-glib-1.0-0 libjson-glib-dev libconfig++8-dev libjson-c-dev libjson-c2
 - sudo apt-get install -y python-rosinstall
 - sudo rosdep init
 - rosdep update
 - echo "source /opt/ros/indigo/setup.bash" >> ~/.bashrc
 - source ~/.bashrc
 - source /opt/ros/indigo/setup.bash
 - mkdir -p ~/catkin_ws/src
 - cd ~/catkin_ws/src
 - catkin_init_workspace
 - wstool init
 - cd ~/catkin_ws
 - catkin_make
 - source devel/setup.bash
 - cd ~/catkin_ws/src
 - wstool set iai_common_msgs --git https://github.com/code-iai/iai_common_msgs.git -y
 - wstool set designator_integration --git https://github.com/code-iai/designator_integration.git -y
 - wstool update
 - cd ~/catkin_ws
 - catkin_make

script:
 - cd ~/catkin_ws/src
 - wstool set semrec --git https://github.com/code-iai/ros-semrec -y
 - wstool update semrec
 - cd ~/catkin_ws
 - catkin_make --pkg semrec -j1
